#!/bin/bash
##NECESSARY JOB SPECIFICATIONS
#SBATCH --job-name=JobName       #Set the job name to "JobName"
#SBATCH --time=0:25:00           #Set the wall clock limit to 0hr and 30min
#SBATCH --ntasks=12      #Request 4 tasks/cores per node
#SBATCH --mem=64G                 #Request 8GB per node 
#SBATCH --output=output.%j       #Send stdout/err to "output.[jobID]" 
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu              #Request the GPU partition/queue
#SBATCH --output=output.%j       #Send stdout/err to "output.[jobID]" 

##OPTIONAL JOB SPECIFICATIONS
##SBATCH --mail-type=ALL              #Send email on all job events
##SBATCH --mail-user=email_address    #Send all emails to email_address 
#
##First Executable Line

# rm -rf output.*
rm -rf core.*
module load CUDA
nvcc majorProject.cu -o majorProject.exe
./majorProject.exe > results.txt


